name: lecture_CC2
channels:
  - cvxgrp
  - conda-forge
  - defaults
dependencies:
  - attrs=19.3.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.9.11
  - certifi=2019.9.11
  - colorama=0.4.1
  - cvxpy=1.0.24
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.6.0
  - dill=0.3.1.1
  - ecos=2.0.7
  - entrypoints=0.3
  - freetype=2.10.0
  - future=0.18.0
  - icc_rt=2019.0.0
  - icu=64.2
  - importlib_metadata=0.23
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.3
  - jpeg=9c
  - jsonschema=3.1.1
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - lapack=3.6.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.0
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gmp=6.1.0
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - matplotlib-base=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - more-itertools=7.2.0
  - msys2-conda-epoch=20160418
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - notebook=6.0.1
  - numpy=1.17.2
  - openssl=1.1.1c
  - osqp=0.6.1
  - pandoc=2.7.3
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pickleshare=0.7.5
  - pip=19.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.10
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.12.3
  - pyreadline=2.1
  - pyrsistent=0.15.4
  - python=3.6.7
  - python-dateutil=2.8.0
  - pywin32=224
  - pywinpty=0.5.5
  - pyzmq=18.1.0
  - qt=5.12.5
  - qtconsole=4.5.5
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.4.0
  - six=1.12.0
  - sqlite=3.30.1
  - terminado=0.8.2
  - testpath=0.4.2
  - tornado=6.0.3
  - traitlets=4.3.3
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wincertstore=0.2
  - winpty=0.4.3
  - zeromq=4.3.2
  - zipp=0.6.0
  - zlib=1.2.11
  - pip:
    - multiprocess==0.70.4
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - scs==1.2.6

