name: lecture_CC2
channels:
  - cvxgrp
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.11.28
  - certifi=2019.11.28
  - cvxcanon=0.1.1
  - cvxpy=1.0.6
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - dill=0.3.0
  - ecos=2.0.5
  - entrypoints=0.3
  - expat=2.2.6
  - fastcache=1.1.0
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - lapack=3.6.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.1.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - multiprocess=0.70.4
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.17.2
  - numpy-base=1.17.2
  - openssl=1.1.1d
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pip=19.2.3
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - ptyprocess=0.6.0
  - pulp=1.6.8
  - pygments=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - python=3.6.9
  - python-dateutil=2.8.0
  - pytz=2019.3
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - scipy=1.2.1
  - scs=1.2.6
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.10.0
  - tornado=6.0.3
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
prefix: /home/schmalen/anaconda3/envs/lecture_CC2

