name: lecture_MLOC
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.3.0
  - absl-py=0.7.1
  - astor=0.8.0
  - astroid=2.2.5
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - c-ares=1.15.0
  - ca-certificates=2019.5.15
  - certifi=2019.6.16
  - cffi=1.12.3
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gast=0.2.2
  - glib=2.56.2
  - gmp=6.1.2
  - grpcio=1.16.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.2
  - ipython=7.7.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.1
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.1
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libsodium=1.0.16
  - libstdcxx-ng=9.1.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - markdown=3.1.1
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.14
  - mkl_random=1.0.2
  - mock=3.0.5
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - ninja=1.9.0
  - notebook=6.0.0
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1c
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.2.2
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - protobuf=3.8.0
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.2
  - pylint=2.3.1
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytorch-cpu=1.1.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.3
  - readline=7.0
  - scikit-learn=0.21.1
  - scipy=1.3.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.29.0
  - tensorboard=1.13.1
  - tensorflow=1.13.1
  - tensorflow-base=1.13.1
  - tensorflow-estimator=1.13.0
  - termcolor=1.1.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - traitlets=4.3.2
  - typed-ast=1.3.4
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - werkzeug=0.15.5
  - wheel=0.33.4
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7

